index:
    path: /
    controller: App\Controller\DefaultController::index

#hello:
#    path: /hello
#    controller: App\Controller\HelloController::index

#article:
#    path: /article/{slug}
#    controller: App\Controller\PostController::show

view_article:
    path: /article/{slug}
    controller: App\Controller\PostController::view

item:
    path: /article/{slug}/item
    controller: App\Controller\PostController::item

blog:
    path: /blog
    controller: App\Controller\PostController::index

create_post:
    path: /new
    controller: App\Controller\PostController::new
